name: Build and Deploy FastAPI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: herrera001/fastapi-app
  DOCKER_TAG: latest
  VPS_HOST: 167.71.62.79
  VPS_USER: root
  VPS_PATH: /home/duka-fastapi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$DOCKER_TAG .

      # Step 4: Push image to Docker Hub
      - name: Push Docker image
        run: docker push $IMAGE_NAME:$DOCKER_TAG

      # Step 5: SSH into VPS and deploy
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ env.VPS_HOST }}
          username: ${{ env.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd $VPS_PATH
            docker compose pull
            docker compose up -d --remove-orphans
